import './globals.scss'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ weight: ['300', '400', '500'], subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<nav className="navbar py-4">
					<div className="container">
						<a href="https://www.mousephenotype.org/" rel="nofollow" className="navbar-brand">
							{/* eslint-disable-next-line @next/next/no-img-element */}
							<img src="/IMPC_logo.svg" className='my-2' alt="IMPC logo" height="50" />
						</a>
					</div>
				</nav>
				{children}
			</body>
		</html>
	)
}
