import './globals.scss'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ weight: ['300', '400', '500'], subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<header>
					<nav className="navbar py-4">
						<div className="container">
							<a href="https://www.mousephenotype.org/" rel="nofollow" className="navbar-brand">
								{/* eslint-disable-next-line @next/next/no-img-element */}
								<img src="/IMPC_logo.svg" className='my-2' alt="IMPC logo" height="50" />
							</a>

							<a href="#explore_data" className="btn btn-secondary text-white">Explore the Data</a>
						</div>
					</nav>
				</header>
				{children}

				<footer className="bg-light">
					<nav className="navbar navbar-expand py-4">
						<div className="container">
							<p className="navbar-brand mb-0">Ayanfe Ibitoye</p>
							
							<ul className="navbar-nav">
								<li className="nav-item"><a className="nav-link" href="https://github.com/cirqlar/phen">Source</a></li>
								<li className="nav-item"><a className="nav-link" href="https://github.com/cirqlar">Profile</a></li>
								<li className="nav-item"><a className="nav-link" href="https://github.com/mpi2/EBI02126-web-developer/blob/main/gene_phenotypes.json">Data</a></li>
							</ul>
						</div>
					</nav>
				</footer>
			</body>
		</html>
	)
}
